'use client'
// import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/Footer";
import { Provider } from "react-redux";
import store from "./store";

// const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-800">
        <Provider store={store}>
          <section className="main-container flex flex-col justify-between">
            <Navbar />
            {children}
            <Footer/>
          </section>
        </Provider>
      </body>
    </html>
  );
}
